### ISSUE TITLE
Generate new LigerMobile iOS application project

### ISSUE THREAD

**Issue by jaredbro** [reachlocal/liger-mobile-framework#5]
Easily create new LigerMobile application projects for all supported platforms with a single generator command (e.g. yo ligermobile new).

This initial create will do the following:

- [x] Investigate iOS project generation options
- [x] [Generate initial directory structure and iOS app project] (https://github.com/reachlocal/generator-ligermobile/issues/7)
- [x] [Generate Xcode workspace] (https://github.com/reachlocal/generator-ligermobile/issues/8)
- [x] [Generate CoCo Pods integration](https://github.com/reachlocal/generator-ligermobile/issues/9)
- [ ] [Run iOS App generation with existing LigerMobile common generator](https://github.com/reachlocal/generator-ligermobile/issues/10)

**Comment by gmoonx1992** [comment]
A similar idea was done during Hackathon 2014: Ignition Day.

Repo: https://stash.lax.reachlocal.com/projects/HAC/repos/optimism/browse

Basically, it was a python script that set up the dependencies, the directory structure, and the app template for iOS and Android. You ran one command from the terminal, and you could start working on a LigerMobile app.

Keep in mind that it was created within 24 hours, so it's not exactly the greatest piece of coding. Also, this was written ~5 months ago, so something might not work anymore. It may still be a good starting point for whoever wants to look at this user story.

**Comment by jaredbro** [comment]
I would recommend that we take a look at Apache Cordova and how they generate an Xcode and Android Studio project from the platform command, 'cordova platform add ios', etc.  This might be something we can borrow, so that we don't have to maintain it ourselves as xcode and android studio change.
